name: retailpulse
version: 1.0.0
config-version: 2
profile: retailpulse
model-paths: ["models"]
snapshot-paths: ["snapshots"]
test-paths: ["tests"]
clean-targets: ["target", "dbt_packages"]

models:
  retailpulse:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table
