output "resource_group_name" { value = azurerm_resource_group.this.name }
output "storage_account_name" { value = azurerm_storage_account.lake.name }
output "filesystem_name" { value = azurerm_storage_data_lake_gen2_filesystem.lake.name }
output "eventhub_namespace" { value = try(azurerm_eventhub_namespace.this[0].name, null) }
output "eventhub_names" { value = sort(keys(azurerm_eventhub.topics)) }
output "data_factory_name" { value = azurerm_data_factory.this.name }
output "databricks_workspace_url" { value = azurerm_databricks_workspace.this.workspace_url }
output "key_vault_name" { value = azurerm_key_vault.this.name }
output "budget_name" { value = azurerm_consumption_budget_subscription.this.name }
